name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: init
      run: git submodule init && git submodule update
    - name: make
      run: cd ./gmake2 && make config=release
